# Generated by Django 5.0.7 on 2024-08-10 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="cvv",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(999),
                ],
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="name",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
