# Generated by Django 5.0.7 on 2024-08-10 19:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_payments_cvv_payments_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payments",
            name="order",
        ),
    ]
