# Generated by Django 5.0.7 on 2024-08-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_remove_payments_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("DC", "Debit Card"),
                    ("PP", "PayPal"),
                    ("GP", "Google Pay"),
                    ("COD", "Cash on Delivery"),
                ],
                max_length=3,
            ),
        ),
    ]
