# Generated by Django 5.0.7 on 2024-08-11 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_alter_payments_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userordersummary",
            name="payments",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.payments",
            ),
        ),
    ]
